### ISSUE TITLE
Do not work

### ISSUE THREAD

**Issue by Asthestarsfalll** [MugishoMp/obsidian-editor-width-slider#3]
After I adjust the slider, the width of editor do not change.

**Comment by MugishoMp** [comment]
O, that's weird, which version of the app are you using?

**Comment by Asthestarsfalll** [comment]
1.3.5 on manjaro linux

**Comment by MugishoMp** [comment]
Do you know if this issue only persists in Manjaro Linux or also in windows or Mac?

**Comment by leofdecarvalho** [comment]
Same for me here. After I adjust the slider, the width of editor do not change. I'm using obsidian 1.3.7 in Windows

**Comment by MugishoMp** [comment]
Oh, okay. Thanks for letting me know. That's a problem. I will try to take a look at it later today. So sorry for the wait in advance.

**Comment by leofdecarvalho** [comment]
Seems that there is "}" missing in the code below:

styleElement.innerText = `
			body {
			--file-line-width: calc(700px + 10 * ${this.settings.sliderPercentage}px);
		`;
Closing the body tag with "}" works for me.

**Comment by MugishoMp** [comment]
@leofdecarvalho Thank you very much for noticing finding the issue. @Asthestarsfalll Sorry that it took this long to get it fixed. But the issue as been addressed in the latest release. So please take a look at it: https://github.com/MugishoMp/obsidian-editor-width-slider/releases/tag/1.0.3

For now I will close this issue. But if any other similar issues arrive please feel free to reopen this issue!

**Comment by wolsoot** [comment]
This is still happening on Windows 10, Obsidian 1.4.5, obsidian-editor-width-slider 1.0.3.
All other community plugins disabled, no community themes installed.

**Comment by MugishoMp** [comment]
Hey, sorry for the late response @wolsoot, I havent been able to take the time to update obsidian yet so I was unaware of this issue. I'm happy to see that @leofdecarvalho was able to find the issue already. I'll try to release a patched version by the end of this day. Thank you @leofdecarvalho!
